"""Curated list of major Indian cities and popular rental localities.

Used by the web UI for the location dropdown. Localities are
curated, not exhaustive — users can still type any locality manually.
"""

from __future__ import annotations

CITIES: dict[str, list[str]] = {
    "Bangalore": [
        "Koramangala",
        "Indiranagar",
        "HSR Layout",
        "Whitefield",
        "Marathahalli",
        "BTM Layout",
        "Jayanagar",
        "Electronic City",
        "Bellandur",
        "Sarjapur Road",
        "JP Nagar",
        "Banashankari",
        "Hebbal",
        "Yelahanka",
        "RT Nagar",
        "Malleswaram",
        "Rajajinagar",
        "Kalyan Nagar",
        "Bommanahalli",
        "Bannerghatta Road",
    ],
    "Mumbai": [
        "Andheri West",
        "Andheri East",
        "Bandra West",
        "Bandra East",
        "Powai",
        "Goregaon",
        "Malad",
        "Kandivali",
        "Borivali",
        "Juhu",
        "Versova",
        "Lower Parel",
        "Worli",
        "Dadar",
        "Vikhroli",
        "Ghatkopar",
        "Thane",
        "Navi Mumbai",
        "Vashi",
        "Mulund",
    ],
    "Delhi": [
        "Connaught Place",
        "Karol Bagh",
        "Saket",
        "Hauz Khas",
        "Greater Kailash",
        "Lajpat Nagar",
        "Vasant Kunj",
        "Dwarka",
        "Rohini",
        "Pitampura",
        "Janakpuri",
        "Mayur Vihar",
        "Mukherjee Nagar",
        "Laxmi Nagar",
        "Defence Colony",
        "South Extension",
        "Rajouri Garden",
        "Chandni Chowk",
        "Paharganj",
        "Civil Lines",
    ],
    "Gurgaon": [
        "Sector 14",
        "Sector 29",
        "Sector 49",
        "Sector 56",
        "Sector 57",
        "DLF Phase 1",
        "DLF Phase 2",
        "DLF Phase 3",
        "DLF Phase 4",
        "DLF Phase 5",
        "Golf Course Road",
        "Golf Course Extension",
        "MG Road",
        "Sohna Road",
        "Cyber City",
        "South City 1",
        "South City 2",
        "Sushant Lok",
        "Palam Vihar",
        "New Gurgaon",
    ],
    "Noida": [
        "Sector 18",
        "Sector 62",
        "Sector 63",
        "Sector 76",
        "Sector 78",
        "Sector 121",
        "Sector 137",
        "Sector 168",
        "Greater Noida",
        "Noida Extension",
        "Indirapuram",
        "Vaishali",
        "Kaushambi",
    ],
    "Hyderabad": [
        "Gachibowli",
        "HITEC City",
        "Madhapur",
        "Kondapur",
        "Banjara Hills",
        "Jubilee Hills",
        "Begumpet",
        "Ameerpet",
        "Kukatpally",
        "Manikonda",
        "Financial District",
        "Miyapur",
        "Nallagandla",
        "Tellapur",
        "Uppal",
        "LB Nagar",
        "Secunderabad",
        "Mehdipatnam",
        "Tolichowki",
    ],
    "Chennai": [
        "T Nagar",
        "Adyar",
        "Velachery",
        "OMR",
        "ECR",
        "Tambaram",
        "Chromepet",
        "Anna Nagar",
        "Nungambakkam",
        "Mylapore",
        "Besant Nagar",
        "Thoraipakkam",
        "Sholinganallur",
        "Porur",
        "Mogappair",
        "Kilpauk",
        "Egmore",
        "Pallavaram",
        "Perambur",
    ],
    "Pune": [
        "Hinjewadi",
        "Wakad",
        "Baner",
        "Aundh",
        "Kothrud",
        "Viman Nagar",
        "Kharadi",
        "Magarpatta",
        "Hadapsar",
        "Koregaon Park",
        "Kalyani Nagar",
        "Pimple Saudagar",
        "Pimpri",
        "Chinchwad",
        "Wagholi",
        "Shivaji Nagar",
        "Deccan",
        "Camp",
        "Bavdhan",
        "Pashan",
    ],
    "Kolkata": [
        "Salt Lake",
        "New Town",
        "Park Street",
        "Howrah",
        "Garia",
        "Behala",
        "Tollygunge",
        "Ballygunge",
        "Alipore",
        "Jadavpur",
        "Dum Dum",
        "Lake Town",
    ],
    "Ahmedabad": [
        "Satellite",
        "Bodakdev",
        "Vastrapur",
        "SG Highway",
        "Prahlad Nagar",
        "Bopal",
        "Thaltej",
        "Maninagar",
        "Naranpura",
        "Navrangpura",
        "Gurukul",
        "Chandkheda",
    ],
    "Kochi": [
        "Kakkanad",
        "Kaloor",
        "Edappally",
        "Vyttila",
        "Palarivattom",
        "Panampilly Nagar",
        "Marine Drive",
        "Fort Kochi",
        "Aluva",
        "InfoPark",
    ],
    "Thiruvananthapuram": [
        "Technopark",
        "Kazhakkoottam",
        "Vellayambalam",
        "Pattom",
        "Sasthamangalam",
        "Kowdiar",
        "Vazhuthacaud",
        "Thycaud",
    ],
}


def all_cities() -> list[str]:
    return sorted(CITIES.keys())


def localities_for(city: str) -> list[str]:
    return CITIES.get(city, [])
